services:
  httpstun_server:
    container_name: httpstun_server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    volumes:
      - ./config:/config
    build:
      context: .
      dockerfile: httpstun_server/Dockerfile
    command: ["httpstun_server", "--config-file", "/config/config.toml"]
  httpstun_client:
    container_name: httpstun_client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    build:
      context: .
      dockerfile: httpstun_client/Dockerfile
    command: ["httpstun_client", "--server-url", "ws://httpstun_server:8080/", "--client-name", "justin", "--client-password", "hunter1234"]